### ISSUE TITLE
Suggestions setting up with gnome-terminal and problem to render the latex text

### ISSUE THREAD

**Issue by firilisinof** [gillescastel/inkscape-shortcut-manager#12]
I tried to configure with gnome-terminal to open the window to insert the text to be rendered by latex, but it ends up opening vim without $$ and no input is not copied to inkscape. See below how I set it up:
```    subprocess.run([
        'gnome-terminal',
        '--geometry', '60x5',
        '--', "vim",
        f"{filename}",
    ])
```
In addition to this problem: in the option to render the text beforehand (`shift + T`), everything opens normally, but when saved the input the rendered text does not appear in inkscape.

any idea why?

**Comment by gillescastel** [comment]
The problem is probably that when executing `gnome-terminal` it doesn't wait for the terminal to close before it returns. I.e.: 

![2020-08-06-10-13-33](https://user-images.githubusercontent.com/7069691/89507975-87830680-d7cd-11ea-8107-8308ac3a423c.gif)

See how the prompt on the left appears immediately after opening a terminal? My script assumes it waits for the terminal to close and then reads the contents of the saved file. With the default behaviour of gnome-terminal, it returns immediately and so the content of the file is empty. 

Adding the `--wait` flag to `gnome-terminal` (introduced in v3.27.1) should probably fix that: 

![2020-08-06-10-15-44](https://user-images.githubusercontent.com/7069691/89508219-e779ad00-d7cd-11ea-87af-9c7f94b523ab.gif)

Let me know if that works!

**Comment by firilisinof** [comment]
Now it worked. Thank you.

**Comment by gillescastel** [comment]
Glad it did!
